Repository try-keep/referral-capital-application, pull requests merged in 2025-06, with the labels that each got.

#2 Feature/dat 2411 fix flinks flow in capital application
  src/app/step/[id]/page.tsx
Labels: size/L

#4 [GRO-2] Remove business age and time in business fields
  src/app/step/[id]/page.tsx
  src/lib/api.ts
  src/lib/supabase.ts
Labels: size/M

#6 [GRO-3] Change Personal Address title
  src/app/step/[id]/page.tsx
Labels: size/XS

#7 [GRO-27] Add userId to flinks tag URL
  src/app/step/[id]/page.tsx
Labels: size/S

#8 [GRO-33] Add segment tracking
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/analytics.tsx
  src/lib/segment.ts
  supabase/.gitignore
  supabase/config.toml
  vercel.json
Labels: size/L

#10 [GRO-38] Standardize schema management
  add-business-id-to-applications.sql
  add-date-of-birth-column.sql
  add-user-id-to-applications.sql
  add_ip_address_column.sql
  dev-server.log
  fix-applications-rls.sql
  fix-users-rls.sql
  setup-supabase.js
  setup-users-table.js
  supabase-businesses-table.sql
  supabase-compliance-table.sql
  supabase-setup.sql
  supabase-users-table.sql
  supabase/migrations/20250628010950_remote_schema.sql
  update-users-rls.sql
Labels: size/XXL
