Repository try-keep/referral-capital-application, pull requests merged in 2025-07, with the labels that each got.

#15 [GRO-40] - Add amplitude to app
  package.json
  src/app/layout.tsx
  src/components/Providers.tsx
  src/components/analytics.tsx
  src/hooks/index.ts
  src/hooks/use-page-segment-analytics.ts
  src/utils/analytics/traits.ts
  src/utils/index.ts
  src/utils/misc/filterObjectEmptyvalues.ts
  src/utils/misc/index.ts
  src/utils/misc/isDefined.ts
Labels: size/L

#16 Revert "[GRO-40] - Add amplitude to app"
  package.json
  src/app/layout.tsx
  src/components/Providers.tsx
  src/components/analytics.tsx
  src/hooks/index.ts
  src/hooks/use-page-segment-analytics.ts
  src/utils/analytics/traits.ts
  src/utils/index.ts
  src/utils/misc/filterObjectEmptyvalues.ts
  src/utils/misc/index.ts
  src/utils/misc/isDefined.ts
Labels: size/L

#14 [GRO-25] Fix incorporation date and entity type data gathering
  src/app/step/[id]/page.tsx
  src/lib/api.ts
  src/lib/businessRegistry.ts
  src/lib/supabase.ts
  supabase/migrations/20250702111842_fix_business_derived_fields_trigger_and_function.sql
  supabase/migrations/20250702204217_add_registry_entity_type_to_business.sql
Labels: size/XL

#18 [GRO-49] - move personalinformation step to its own component
  src/app/step/[id]/page.tsx
  src/components/forms/PersonalInformation.tsx
  src/components/forms/index.ts
  src/types/form-data.ts
  src/types/index.ts
Labels: size/XL

#17 Revert "Revert "[GRO-40] - Add amplitude to app""
  package.json
  src/app/layout.tsx
  src/components/Providers.tsx
  src/components/analytics.tsx
  src/hooks/index.ts
  src/hooks/use-page-segment-analytics.ts
  src/utils/analytics/traits.ts
  src/utils/index.ts
  src/utils/misc/filterObjectEmptyvalues.ts
  src/utils/misc/index.ts
  src/utils/misc/isDefined.ts
Labels: size/L

#13 [GRO-18] Add upload bank statements path
  src/app/api/bank-statement/route.ts
  src/app/step/[id]/page.tsx
  src/lib/api.ts
  src/types/form-data.ts
  supabase/migrations/20250701000000_create_bank_statements_table.sql
  supabase/migrations/20250701000001_create_bank_statements_bucket.sql
Labels: size/XL

#19 [GRO-18] Request 6 months of bank statements
  src/app/step/[id]/page.tsx
Labels: size/S

#20 [GRO-51] Allow early flow termination when user is not authorized to secure financing
  src/app/step/[id]/page.tsx
  src/lib/api.ts
  src/lib/supabase.ts
  supabase/migrations/20250703215146_add_owns_more_than_50pct_to_applications.sql
Labels: size/L

#21 [GRO-52] - Fix DX while running npm run dev as validations are not being handled properlyc
  src/app/step/[id]/page.tsx
Labels: size/L

#24 [GRO-57] Deprecate LP and use webflow instead
  .github/workflows/ci.yml
  next.config.js
  src/app/page.tsx
  src/app/step/[id]/page.tsx
  src/app/success/page.tsx
Labels: size/XXL

#25 [GRO-59] - Add loader to flinks
  src/components/forms/BankInformation.tsx
Labels: size/M

#32 [GRO-73] - Personal Information Section
  src/app/application/v2/email-address/page.tsx
  src/app/application/v2/personal-address/page.tsx
  src/app/application/v2/personal-details/page.tsx
  src/app/globals.css
  src/components/AddressAutocompleteInput.tsx
  src/components/forms/application/v2/ApplicationStepWrapper.tsx
  src/components/forms/application/v2/email-address.tsx
  src/components/forms/application/v2/funding-amount.tsx
  src/components/forms/application/v2/personal-address.tsx
  src/components/forms/application/v2/personal-details.tsx
  src/components/forms/application/v2/profile-analysis.tsx
  src/components/forms/application/v2/submit.tsx
  src/components/forms/application/v2/time-in-business.tsx
  src/constants/application/index.ts
  src/contexts/application/ApplicationContext.tsx
  src/utils/misc/isDefined.ts
Labels: size/XL

#33 [GRO-74] Add core of business information section
  src/app/application/v2/bank-account-connection/page.tsx
  src/app/application/v2/business-address/page.tsx
  src/app/application/v2/business-entity-type/page.tsx
  src/app/application/v2/business-information/page.tsx
  src/app/application/v2/business-ownership/page.tsx
  src/app/application/v2/existing-loans/page.tsx
  src/app/application/v2/funding-purpose/page.tsx
  src/app/application/v2/funding-timeline/page.tsx
  src/app/application/v2/number-of-employees/page.tsx
  src/app/application/v2/type-of-funding/page.tsx
  src/components/forms/application/v2/bank-account-connection.tsx
  src/components/forms/application/v2/business-address.tsx
  src/components/forms/application/v2/business-entity-type.tsx
  src/components/forms/application/v2/business-information.tsx
  src/components/forms/application/v2/business-ownership.tsx
  src/components/forms/application/v2/existing-loans.tsx
  src/components/forms/application/v2/funding-purpose.tsx
  src/components/forms/application/v2/funding-timeline.tsx
  src/components/forms/application/v2/number-of-employees.tsx
  src/components/forms/application/v2/type-of-funding.tsx
  src/constants/application/index.ts
Labels: size/XXL

#34 [GRO-75] Add business address page with auto-complete
  src/components/forms/application/v2/business-address.tsx
  src/constants/application/index.ts
  src/lib/api.ts
  src/lib/supabase.ts
  supabase/migrations/20250710231022_add_business_address_fields.sql
Labels: size/L

#35 [GRO-76] Implement bank account connection + upload
  .github/workflows/ci.yml
  src/app/globals.css
  src/components/forms/application/v2/bank-account-connection.tsx
  src/constants/application/index.ts
Labels: size/XL

#37 [GRO-89] Fix field names for review and submit page
  src/components/forms/application/v2/submit.tsx
Labels: size/L
